import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { ALL_SCOPE_SUBJECTS } from '../scopes.js';
import { logger } from '../logger.js';

export interface InitAppsFlags {
  path?: string;
}

interface AppSpec {
  dir: string;
  name: string;
  scopePrefix: 'read' | 'write';
  storeHint: string;
}

const APPS: AppSpec[] = [
  { dir: 'syncify-read', name: 'Syncify (Read-only)', scopePrefix: 'read', storeHint: 'Production' },
  { dir: 'syncify-write', name: 'Syncify (Write)', scopePrefix: 'write', storeHint: 'Dev' },
];

function buildToml(app: AppSpec): string {
  const scopes = ALL_SCOPE_SUBJECTS.map((s) => `${app.scopePrefix}_${s}`).join(',');
  return `# Generated by \`syncify init-apps\` — a local template for a Shopify Dev
# Dashboard app config. Nothing has been created on Shopify yet; this file
# alone does nothing on its own. To actually create/link and deploy it:
#
#   cd ${app.dir}
#   shopify app init --client-id <id>   # if you already created the app via the Dev Dashboard UI, or:
#   shopify app config link             # to link an existing app interactively
#   shopify app deploy                  # to push these scopes to Shopify
#
# Then install the resulting app on your ${app.storeHint} store (Dev
# Dashboard → your app → Home → Install app), and copy its Client ID (this
# file's client_id, once linked) and Client Secret (Dev Dashboard →
# Settings) into .env — see README.md "Getting the Production/Dev token,
# Option B".

name = "${app.name}"
client_id = ""
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[access_scopes]
scopes = "${scopes}"

[auth]
redirect_urls = ["https://shopify.dev/apps/default-app-home"]
`;
}

export async function runInitApps(flags: InitAppsFlags): Promise<void> {
  const baseDir = resolve(process.cwd(), flags.path ?? 'apps');

  for (const app of APPS) {
    const appDir = resolve(baseDir, app.dir);
    mkdirSync(appDir, { recursive: true });

    const tomlPath = resolve(appDir, 'shopify.app.toml');
    if (existsSync(tomlPath)) {
      logger.warn(`${tomlPath} already exists — overwriting.`);
    }
    writeFileSync(tomlPath, buildToml(app), 'utf-8');
    logger.success(`Wrote ${tomlPath}`);
  }

  logger.info(
    "\nThese are local templates only — nothing was created on Shopify. See each shopify.app.toml's header comment for the manual steps to create/link, deploy, and install each app."
  );
}
